/* tslint:disable */
/* eslint-disable */
/**
 * Interopdata API
 * The Interopdata public API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateDataExportLinkDtoCustomer } from './CreateDataExportLinkDtoCustomer';
import {
    CreateDataExportLinkDtoCustomerFromJSON,
    CreateDataExportLinkDtoCustomerFromJSONTyped,
    CreateDataExportLinkDtoCustomerToJSON,
} from './CreateDataExportLinkDtoCustomer';

/**
 * 
 * @export
 * @interface CreateDataExportLinkDto
 */
export interface CreateDataExportLinkDto {
    /**
     * The id of the customer associated with the data-export link. Must be specified if `customer` is not.
     * @type {string}
     * @memberof CreateDataExportLinkDto
     */
    customerId?: string;
    /**
     * 
     * @type {CreateDataExportLinkDtoCustomer}
     * @memberof CreateDataExportLinkDto
     */
    customer?: CreateDataExportLinkDtoCustomer;
}

/**
 * Check if a given object implements the CreateDataExportLinkDto interface.
 */
export function instanceOfCreateDataExportLinkDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateDataExportLinkDtoFromJSON(json: any): CreateDataExportLinkDto {
    return CreateDataExportLinkDtoFromJSONTyped(json, false);
}

export function CreateDataExportLinkDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDataExportLinkDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'customerId': !exists(json, 'customerId') ? undefined : json['customerId'],
        'customer': !exists(json, 'customer') ? undefined : CreateDataExportLinkDtoCustomerFromJSON(json['customer']),
    };
}

export function CreateDataExportLinkDtoToJSON(value?: CreateDataExportLinkDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'customerId': value.customerId,
        'customer': CreateDataExportLinkDtoCustomerToJSON(value.customer),
    };
}

