/* tslint:disable */
/* eslint-disable */
/**
 * Interopdata API
 * The Interopdata public API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAccessTokenDto
 */
export interface CreateAccessTokenDto {
    /**
     * The OAuth grant type. Must be "authorization_code".
     * @type {string}
     * @memberof CreateAccessTokenDto
     */
    grantType: string;
    /**
     * The OAuth exchange code.
     * @type {string}
     * @memberof CreateAccessTokenDto
     */
    code: string;
    /**
     * The source IP address of the exchange request.
     * @type {string}
     * @memberof CreateAccessTokenDto
     */
    ip?: string;
}

/**
 * Check if a given object implements the CreateAccessTokenDto interface.
 */
export function instanceOfCreateAccessTokenDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "grantType" in value;
    isInstance = isInstance && "code" in value;

    return isInstance;
}

export function CreateAccessTokenDtoFromJSON(json: any): CreateAccessTokenDto {
    return CreateAccessTokenDtoFromJSONTyped(json, false);
}

export function CreateAccessTokenDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAccessTokenDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'grantType': json['grant_type'],
        'code': json['code'],
        'ip': !exists(json, 'ip') ? undefined : json['ip'],
    };
}

export function CreateAccessTokenDtoToJSON(value?: CreateAccessTokenDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'grant_type': value.grantType,
        'code': value.code,
        'ip': value.ip,
    };
}

