/* tslint:disable */
/* eslint-disable */
/**
 * Interopdata API
 * The Interopdata public API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateDataExportDto
 */
export interface CreateDataExportDto {
    /**
     * The list of slug of the datasets to export
     * @type {Array<string>}
     * @memberof CreateDataExportDto
     */
    datasets: Array<string>;
}

/**
 * Check if a given object implements the CreateDataExportDto interface.
 */
export function instanceOfCreateDataExportDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "datasets" in value;

    return isInstance;
}

export function CreateDataExportDtoFromJSON(json: any): CreateDataExportDto {
    return CreateDataExportDtoFromJSONTyped(json, false);
}

export function CreateDataExportDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDataExportDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'datasets': json['datasets'],
    };
}

export function CreateDataExportDtoToJSON(value?: CreateDataExportDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'datasets': value.datasets,
    };
}

