/* tslint:disable */
/* eslint-disable */
/**
 * Interopdata API
 * The Interopdata public API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Customer
 */
export interface Customer {
    /**
     * A unique identifier of the customer in your system.
     * @type {string}
     * @memberof Customer
     */
    id: string;
    /**
     * Customer’s email address. It’s displayed alongside the customer in your dashboard and can be useful for searching and tracking. This may be up to 512 characters.
     * @type {object}
     * @memberof Customer
     */
    email: object | null;
    /**
     * 
     * @type {object}
     * @memberof Customer
     */
    description: object | null;
    /**
     * Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     * @type {object}
     * @memberof Customer
     */
    metadata: object;
    /**
     * Customer’s preferred languages, ordered by preference.
     * @type {Array<string>}
     * @memberof Customer
     */
    preferredLocales: Array<string>;
}

/**
 * Check if a given object implements the Customer interface.
 */
export function instanceOfCustomer(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "metadata" in value;
    isInstance = isInstance && "preferredLocales" in value;

    return isInstance;
}

export function CustomerFromJSON(json: any): Customer {
    return CustomerFromJSONTyped(json, false);
}

export function CustomerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Customer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
        'description': json['description'],
        'metadata': json['metadata'],
        'preferredLocales': json['preferredLocales'],
    };
}

export function CustomerToJSON(value?: Customer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'email': value.email,
        'description': value.description,
        'metadata': value.metadata,
        'preferredLocales': value.preferredLocales,
    };
}

