/* tslint:disable */
/* eslint-disable */
/**
 * Interopdata API
 * The Interopdata public API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataExportDatasetDownload
 */
export interface DataExportDatasetDownload {
    /**
     * 
     * @type {number}
     * @memberof DataExportDatasetDownload
     */
    size: number;
    /**
     * 
     * @type {string}
     * @memberof DataExportDatasetDownload
     */
    filename: string;
    /**
     * 
     * @type {string}
     * @memberof DataExportDatasetDownload
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof DataExportDatasetDownload
     */
    contentType: string;
}

/**
 * Check if a given object implements the DataExportDatasetDownload interface.
 */
export function instanceOfDataExportDatasetDownload(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "size" in value;
    isInstance = isInstance && "filename" in value;
    isInstance = isInstance && "url" in value;
    isInstance = isInstance && "contentType" in value;

    return isInstance;
}

export function DataExportDatasetDownloadFromJSON(json: any): DataExportDatasetDownload {
    return DataExportDatasetDownloadFromJSONTyped(json, false);
}

export function DataExportDatasetDownloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataExportDatasetDownload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'size': json['size'],
        'filename': json['filename'],
        'url': json['url'],
        'contentType': json['contentType'],
    };
}

export function DataExportDatasetDownloadToJSON(value?: DataExportDatasetDownload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'size': value.size,
        'filename': value.filename,
        'url': value.url,
        'contentType': value.contentType,
    };
}

