/* tslint:disable */
/* eslint-disable */
/**
 * Interopdata API
 * The Interopdata public API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataExportLink
 */
export interface DataExportLink {
    /**
     * The URL of the data-export link. The root part is assocaited project `Redirect URL`. You should point your user to this URL.
     * @type {string}
     * @memberof DataExportLink
     */
    url: string;
}

/**
 * Check if a given object implements the DataExportLink interface.
 */
export function instanceOfDataExportLink(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "url" in value;

    return isInstance;
}

export function DataExportLinkFromJSON(json: any): DataExportLink {
    return DataExportLinkFromJSONTyped(json, false);
}

export function DataExportLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataExportLink {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': json['url'],
    };
}

export function DataExportLinkToJSON(value?: DataExportLink | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
    };
}

