/**
 * Interopdata API
 * The Interopdata public API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import type { AccessToken, CreateAccessTokenDto, CreateCustomerDto, CreateDataExportDto, CreateDataExportLinkDto, Customer, DataExportLink, Dataset } from '../models';
export interface CreateCustomerRequest {
    createCustomerDto: CreateCustomerDto;
}
export interface CreateDataExportRequest {
    createDataExportDto: CreateDataExportDto;
}
export interface CreateDataExportLinkRequest {
    createDataExportLinkDto: CreateDataExportLinkDto;
}
export interface CreateOAuthTokenRequest {
    createAccessTokenDto: CreateAccessTokenDto;
}
export interface CustomersListRequest {
    createCustomerDto: CreateCustomerDto;
}
/**
 *
 */
export declare class DefaultApi extends runtime.BaseAPI {
    /**
     */
    createCustomerRaw(requestParameters: CreateCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Customer>>;
    /**
     */
    createCustomer(requestParameters: CreateCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Customer>;
    /**
     */
    createDataExportRaw(requestParameters: CreateDataExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;
    /**
     */
    createDataExport(requestParameters: CreateDataExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;
    /**
     */
    createDataExportLinkRaw(requestParameters: CreateDataExportLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataExportLink>>;
    /**
     */
    createDataExportLink(requestParameters: CreateDataExportLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataExportLink>;
    /**
     */
    createOAuthTokenRaw(requestParameters: CreateOAuthTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccessToken>>;
    /**
     */
    createOAuthToken(requestParameters: CreateOAuthTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccessToken>;
    /**
     */
    customersListRaw(requestParameters: CustomersListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Customer>>>;
    /**
     */
    customersList(requestParameters: CustomersListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Customer>>;
    /**
     */
    datasetsListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Dataset>>>;
    /**
     */
    datasetsList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Dataset>>;
}
