/**
 * Interopdata API
 * The Interopdata public API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import type { AccessToken, CreateAccessTokenDto, CreateCustomerDto, CreateDataExportDto, CreateDataExportLinkDto, Customer, DataExport, DataExportDataset, DataExportDatasetDownload, DataExportLink, Dataset, Locale, Project } from '../models';
export interface CreateCustomerRequest {
    createCustomerDto: CreateCustomerDto;
}
export interface CreateDataExportRequest {
    createDataExportDto: CreateDataExportDto;
}
export interface CreateDataExportDatasetDownloadRequest {
    id: string;
}
export interface CreateDataExportLinkRequest {
    createDataExportLinkDto: CreateDataExportLinkDto;
}
export interface CreateOAuthTokenRequest {
    createAccessTokenDto: CreateAccessTokenDto;
}
export interface CustomersListRequest {
    createCustomerDto: CreateCustomerDto;
}
export interface DataExportDatasetRetrieveRequest {
    id: string;
}
export interface DataExportRetrieveRequest {
    id: string;
}
export interface SealDataExportDatasetRequest {
    id: string;
}
/**
 *
 */
export declare class DefaultApi extends runtime.BaseAPI {
    /**
     */
    createCustomerRaw(requestParameters: CreateCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Customer>>;
    /**
     */
    createCustomer(requestParameters: CreateCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Customer>;
    /**
     */
    createDataExportRaw(requestParameters: CreateDataExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;
    /**
     */
    createDataExport(requestParameters: CreateDataExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;
    /**
     */
    createDataExportDatasetDownloadRaw(requestParameters: CreateDataExportDatasetDownloadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataExportDatasetDownload>>;
    /**
     */
    createDataExportDatasetDownload(requestParameters: CreateDataExportDatasetDownloadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataExportDatasetDownload>;
    /**
     */
    createDataExportLinkRaw(requestParameters: CreateDataExportLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataExportLink>>;
    /**
     */
    createDataExportLink(requestParameters: CreateDataExportLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataExportLink>;
    /**
     */
    createOAuthTokenRaw(requestParameters: CreateOAuthTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccessToken>>;
    /**
     */
    createOAuthToken(requestParameters: CreateOAuthTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccessToken>;
    /**
     */
    customerRetrieveRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Customer>>;
    /**
     */
    customerRetrieve(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Customer>;
    /**
     */
    customersListRaw(requestParameters: CustomersListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Customer>>>;
    /**
     */
    customersList(requestParameters: CustomersListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Customer>>;
    /**
     */
    dataExportDatasetRetrieveRaw(requestParameters: DataExportDatasetRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataExportDataset>>;
    /**
     */
    dataExportDatasetRetrieve(requestParameters: DataExportDatasetRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataExportDataset>;
    /**
     */
    dataExportRetrieveRaw(requestParameters: DataExportRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataExport>>;
    /**
     */
    dataExportRetrieve(requestParameters: DataExportRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataExport>;
    /**
     */
    dataExportsListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DataExport>>>;
    /**
     */
    dataExportsList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DataExport>>;
    /**
     */
    datasetsListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Dataset>>>;
    /**
     */
    datasetsList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Dataset>>;
    /**
     */
    localesListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Locale>>>;
    /**
     */
    localesList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Locale>>;
    /**
     */
    projectRetreiveRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Project>>>;
    /**
     */
    projectRetreive(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Project>>;
    /**
     */
    sealDataExportDatasetRaw(requestParameters: SealDataExportDatasetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;
    /**
     */
    sealDataExportDataset(requestParameters: SealDataExportDatasetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;
}
