/**
 * Interopdata API
 * The Interopdata public API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface AccessToken
 */
export interface AccessToken {
    /**
     *
     * @type {string}
     * @memberof AccessToken
     */
    customerId: string;
    /**
     *
     * @type {string}
     * @memberof AccessToken
     */
    accessToken: string;
    /**
     * A string representing the token expiration date in the ISO 8601 format according to universal time.
     * @type {string}
     * @memberof AccessToken
     */
    expiredAt: string;
}
/**
 * Check if a given object implements the AccessToken interface.
 */
export declare function instanceOfAccessToken(value: object): boolean;
export declare function AccessTokenFromJSON(json: any): AccessToken;
export declare function AccessTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessToken;
export declare function AccessTokenToJSON(value?: AccessToken | null): any;
