/**
 * Interopdata API
 * The Interopdata public API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface CreateAccessTokenDto
 */
export interface CreateAccessTokenDto {
    /**
     * The OAuth grant type. Must be "authorization_code".
     * @type {string}
     * @memberof CreateAccessTokenDto
     */
    grantType: string;
    /**
     * The OAuth exchange code.
     * @type {string}
     * @memberof CreateAccessTokenDto
     */
    code: string;
    /**
     * The source IP address of the exchange request.
     * @type {string}
     * @memberof CreateAccessTokenDto
     */
    ip?: string;
}
/**
 * Check if a given object implements the CreateAccessTokenDto interface.
 */
export declare function instanceOfCreateAccessTokenDto(value: object): boolean;
export declare function CreateAccessTokenDtoFromJSON(json: any): CreateAccessTokenDto;
export declare function CreateAccessTokenDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAccessTokenDto;
export declare function CreateAccessTokenDtoToJSON(value?: CreateAccessTokenDto | null): any;
