/**
 * Interopdata API
 * The Interopdata public API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { CreateDataExportLinkDtoCustomer } from './CreateDataExportLinkDtoCustomer';
/**
 *
 * @export
 * @interface CreateDataExportLinkDto
 */
export interface CreateDataExportLinkDto {
    /**
     * The id of the customer associated with the data-export link. Must be specified if `customer` is not.
     * @type {string}
     * @memberof CreateDataExportLinkDto
     */
    customerId?: string;
    /**
     *
     * @type {CreateDataExportLinkDtoCustomer}
     * @memberof CreateDataExportLinkDto
     */
    customer?: CreateDataExportLinkDtoCustomer;
}
/**
 * Check if a given object implements the CreateDataExportLinkDto interface.
 */
export declare function instanceOfCreateDataExportLinkDto(value: object): boolean;
export declare function CreateDataExportLinkDtoFromJSON(json: any): CreateDataExportLinkDto;
export declare function CreateDataExportLinkDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDataExportLinkDto;
export declare function CreateDataExportLinkDtoToJSON(value?: CreateDataExportLinkDto | null): any;
