/**
 * Interopdata API
 * The Interopdata public API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * The created or update customer associated with the data-export link. Must be specified if `customerId` is not.
 * @export
 * @interface CreateDataExportLinkDtoCustomer
 */
export interface CreateDataExportLinkDtoCustomer {
    /**
     * A unique identifier of the customer in your system.
     * @type {string}
     * @memberof CreateDataExportLinkDtoCustomer
     */
    id: string;
    /**
     * Customer’s email address. It’s displayed alongside the customer in your dashboard and can be useful for searching and tracking. This may be up to 512 characters.
     * @type {string}
     * @memberof CreateDataExportLinkDtoCustomer
     */
    email?: string;
    /**
     * The customer’s full name or business name.
     * @type {string}
     * @memberof CreateDataExportLinkDtoCustomer
     */
    name?: string;
    /**
     * An arbitrary string that you can attach to a customer object. It is displayed alongside the customer in the dashboard.
     * @type {string}
     * @memberof CreateDataExportLinkDtoCustomer
     */
    description?: string;
    /**
     * Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     * @type {object}
     * @memberof CreateDataExportLinkDtoCustomer
     */
    metadata?: object;
    /**
     * Customer’s preferred languages, ordered by preference.
     * @type {Array<string>}
     * @memberof CreateDataExportLinkDtoCustomer
     */
    preferredLocales?: Array<string>;
}
/**
 * Check if a given object implements the CreateDataExportLinkDtoCustomer interface.
 */
export declare function instanceOfCreateDataExportLinkDtoCustomer(value: object): boolean;
export declare function CreateDataExportLinkDtoCustomerFromJSON(json: any): CreateDataExportLinkDtoCustomer;
export declare function CreateDataExportLinkDtoCustomerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDataExportLinkDtoCustomer;
export declare function CreateDataExportLinkDtoCustomerToJSON(value?: CreateDataExportLinkDtoCustomer | null): any;
