/**
 * Interopdata API
 * The Interopdata public API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Customer
 */
export interface Customer {
    /**
     * A unique identifier of the customer in your system.
     * @type {string}
     * @memberof Customer
     */
    id: string;
    /**
     * Customer’s email address. It’s displayed alongside the customer in your dashboard and can be useful for searching and tracking. This may be up to 512 characters.
     * @type {object}
     * @memberof Customer
     */
    email: object | null;
    /**
     *
     * @type {object}
     * @memberof Customer
     */
    description: object | null;
    /**
     * Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     * @type {object}
     * @memberof Customer
     */
    metadata: object;
    /**
     * Customer’s preferred languages, ordered by preference.
     * @type {Array<string>}
     * @memberof Customer
     */
    preferredLocales: Array<string>;
}
/**
 * Check if a given object implements the Customer interface.
 */
export declare function instanceOfCustomer(value: object): boolean;
export declare function CustomerFromJSON(json: any): Customer;
export declare function CustomerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Customer;
export declare function CustomerToJSON(value?: Customer | null): any;
