/**
 * Interopdata API
 * The Interopdata public API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { DataExportDataset } from './DataExportDataset';
/**
 *
 * @export
 * @interface DataExport
 */
export interface DataExport {
    /**
     *
     * @type {string}
     * @memberof DataExport
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof DataExport
     */
    createdAt: string;
    /**
     *
     * @type {Array<DataExportDataset>}
     * @memberof DataExport
     */
    datasets: Array<DataExportDataset>;
}
/**
 * Check if a given object implements the DataExport interface.
 */
export declare function instanceOfDataExport(value: object): boolean;
export declare function DataExportFromJSON(json: any): DataExport;
export declare function DataExportFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataExport;
export declare function DataExportToJSON(value?: DataExport | null): any;
