/**
 * Interopdata API
 * The Interopdata public API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface DataExportLink
 */
export interface DataExportLink {
    /**
     * The URL of the data-export link. The root part is assocaited project `Redirect URL`. You should point your user to this URL.
     * @type {string}
     * @memberof DataExportLink
     */
    url: string;
}
/**
 * Check if a given object implements the DataExportLink interface.
 */
export declare function instanceOfDataExportLink(value: object): boolean;
export declare function DataExportLinkFromJSON(json: any): DataExportLink;
export declare function DataExportLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataExportLink;
export declare function DataExportLinkToJSON(value?: DataExportLink | null): any;
