/**
 * Interopdata API
 * The Interopdata public API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface DataExportDatasetDownload
 */
export interface DataExportDatasetDownload {
    /**
     *
     * @type {number}
     * @memberof DataExportDatasetDownload
     */
    size: number;
    /**
     *
     * @type {string}
     * @memberof DataExportDatasetDownload
     */
    filename: string;
    /**
     *
     * @type {string}
     * @memberof DataExportDatasetDownload
     */
    url: string;
    /**
     *
     * @type {string}
     * @memberof DataExportDatasetDownload
     */
    contentType: string;
}
/**
 * Check if a given object implements the DataExportDatasetDownload interface.
 */
export declare function instanceOfDataExportDatasetDownload(value: object): boolean;
export declare function DataExportDatasetDownloadFromJSON(json: any): DataExportDatasetDownload;
export declare function DataExportDatasetDownloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataExportDatasetDownload;
export declare function DataExportDatasetDownloadToJSON(value?: DataExportDatasetDownload | null): any;
