/**
 * Interopdata API
 * The Interopdata public API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface DataExportDataset
 */
export interface DataExportDataset {
    /**
     *
     * @type {string}
     * @memberof DataExportDataset
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof DataExportDataset
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof DataExportDataset
     */
    description: string;
    /**
     *
     * @type {string}
     * @memberof DataExportDataset
     */
    icon: string;
    /**
     *
     * @type {string}
     * @memberof DataExportDataset
     */
    status: string;
    /**
     *
     * @type {string}
     * @memberof DataExportDataset
     */
    size?: string;
}
/**
 * Check if a given object implements the DataExportDataset interface.
 */
export declare function instanceOfDataExportDataset(value: object): boolean;
export declare function DataExportDatasetFromJSON(json: any): DataExportDataset;
export declare function DataExportDatasetFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataExportDataset;
export declare function DataExportDatasetToJSON(value?: DataExportDataset | null): any;
