/**
 * Interopdata API
 * The Interopdata public API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Locale
 */
export interface Locale {
    /**
     *
     * @type {string}
     * @memberof Locale
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof Locale
     */
    displayName: string;
    /**
     *
     * @type {string}
     * @memberof Locale
     */
    locale: string;
    /**
     *
     * @type {boolean}
     * @memberof Locale
     */
    _default: boolean;
}
/**
 * Check if a given object implements the Locale interface.
 */
export declare function instanceOfLocale(value: object): boolean;
export declare function LocaleFromJSON(json: any): Locale;
export declare function LocaleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Locale;
export declare function LocaleToJSON(value?: Locale | null): any;
