/**
 * Interopdata API
 * The Interopdata public API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Project
 */
export interface Project {
    /**
     *
     * @type {string}
     * @memberof Project
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof Project
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof Project
     */
    slug: string;
}
/**
 * Check if a given object implements the Project interface.
 */
export declare function instanceOfProject(value: object): boolean;
export declare function ProjectFromJSON(json: any): Project;
export declare function ProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): Project;
export declare function ProjectToJSON(value?: Project | null): any;
